/**
 * Fog Node – Schema Validator
 * ─────────────────────────────────────────────────────────────────────────────
 * Stage 1 of the 5-stage fog processing pipeline.
 *
 * Validates each incoming MQTT payload against a strict JSON schema.
 * Malformed payloads are rejected immediately and never forwarded to the cloud,
 * saving API Gateway / Lambda invocations for genuinely corrupted data.
 *
 * Design choice: Using AJV (Another JSON Validator) with JSON Schema Draft-07
 * for schema validation. AJV is the de-facto standard for Node.js schema
 * validation, offering sub-millisecond performance through JIT compilation
 * of validation functions [Ajv documentation, 2024].
 */

import Ajv from 'ajv';

const ajv = new Ajv({ allErrors: true });

// JSON Schema for sensor payloads
// Matches the structure generated by sensors/sensors/base_sensor.py
const sensorPayloadSchema = {
  type: 'object',
  required: ['sensor_id', 'type', 'value', 'unit', 'timestamp', 'seq'],
  properties: {
    sensor_id: {
      type: 'string',
      minLength: 3,
      maxLength: 32,
      description: 'Unique sensor identifier'
    },
    type: {
      type: 'string',
      enum: ['temperature', 'vibration', 'humidity', 'pressure', 'power_consumption'],
      description: 'Sensor category'
    },
    value: {
      type: 'number',
      description: 'Raw sensor reading'
    },
    unit: {
      type: 'string',
      minLength: 1,
      description: 'Physical unit of measurement'
    },
    timestamp: {
      type: 'string',
      description: 'ISO 8601 UTC timestamp'
    },
    seq: {
      type: 'integer',
      minimum: 1,
      description: 'Monotonic sequence number for ordering'
    }
  },
  additionalProperties: false
};

// Compile the schema once at startup (AJV caches it)
const validateFn = ajv.compile(sensorPayloadSchema);

/**
 * Validate a parsed payload object against the sensor schema.
 *
 * @param {object} payload - Parsed JSON object from MQTT message
 * @returns {{ valid: boolean, errors: string[]|null, payload: object|null }}
 */
export function validate(payload) {
  const valid = validateFn(payload);

  if (!valid) {
    const errors = validateFn.errors.map(e => `${e.instancePath} ${e.message}`);
    return { valid: false, errors, payload: null };
  }

  return { valid: true, errors: null, payload };
}

/**
 * Parse and validate raw MQTT message bytes.
 *
 * @param {Buffer} message - Raw MQTT message buffer
 * @returns {{ valid: boolean, errors: string[]|null, payload: object|null }}
 */
export function parseAndValidate(message) {
  let parsed;
  try {
    parsed = JSON.parse(message.toString('utf8'));
  } catch (err) {
    return { valid: false, errors: [`JSON parse error: ${err.message}`], payload: null };
  }

  return validate(parsed);
}
